apiVersion: 1

datasources:
  - name: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: postgres
    database: postgres
    jsonData:
      sslmode: "disable"